### ISSUE TITLE
Empty string not a valid value

### ISSUE THREAD

**Issue by agalpin** [kreuzwerker/envplate#15]
Feature Request
Given:
export PREFIX=

config:
my_prefix="${PREFIX}"

or even:
my_prefix="${PREFIX:-}"

expect:
my_prefix=""

actual:
requires undeclared environment variable 'FUNCTION_PREFIX', no default is given
requires undeclared environment variable 'FUNCTION_PREFIX:-', no default is given

Request: When a empty default is specifically given allow it, so allow ${PREFIX:-}, or another way of having no value

**Comment by yawn** [comment]
Release 0.0.8, including the fix
