### ISSUE TITLE
Syntax error running ep on RPI

### ISSUE THREAD

**Issue by memolipd** [kreuzwerker/envplate#18]
Base image: Hypriot/rpi-node
OS: Hypriot 0.6.1 - http://blog.hypriot.com/downloads/

```Step 23 : RUN curl -sLo /usr/local/bin/ep https://github.com/kreuzwerker/envplate/releases/download/v0.0.8/ep-linux && chmod +x /usr/local/bin/ep```
``` ---> Running in 38da1704a20d```
``` ---> 6c2ede3e1c94```
```Removing intermediate container 38da1704a20d```
```Step 24 : ADD config/interfaces /etc/network/interfaces```
``` ---> e8751d0eafcc```
```Removing intermediate container 29b6fe0e8b58```
```Step 25 : RUN ep /etc/network/interfaces```
``` ---> Running in 44dce7cb7251```
```/usr/local/bin/ep: 1: /usr/local/bin/ep: Syntax error: end of file unexpected (expecting ")")```
```The command '/bin/sh -c ep /etc/network/interfaces' returned a non-zero code: 2```

any idea what could be causing this?

**Comment by yawn** [comment]
Can you attach the config file(s) that `ep` is parsing?

**Comment by memolipd** [comment]
sure:

```interface=ap0
driver=${RADIO_DRIVER}
country_code=${AP_COUNTRY}
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
ssid=${AP_SSID}
hw_mode=g
channel=${AP_CHAN}
beacon_int=100
auth_algs=1
wpa=0
macaddr_acl=0
wmm_enabled=1
ap_isolate=1
ieee80211n=1```

I dont think its to do with the file, its poping up the same error on every file, even files without any envs in.

I think its more to do with the Pi using being arm rather than x64/x86 - anyway to fix this?

**Comment by yawn** [comment]
Hmm - it's possible! Currently the release is not cross-compiled (or tested for that matter) for anything else then x64. Have you tried cross-compiling from source to `linux/arm` and using that? If this fixes your problem, I'll probably add `gox` to the project and provide a release for all possible platforms.

**Comment by memolipd** [comment]
that's a bit beyond me!

I'll have to look into a work around

**Comment by yawn** [comment]
I locally cross compiled `ep` for ARM 7 linux: [ep-rpi.gz](https://github.com/kreuzwerker/envplate/files/93971/ep-rpi.gz). Can you try that out and report back?

**Comment by yawn** [comment]
Any news regarding the custom build @memolipd ?

**Comment by yawn** [comment]
Ping @memolipd

**Comment by memolipd** [comment]
Sorry, been busy with other work. I will definitely give it a try when I finish my current project. Next week some time at the latest

**Comment by memolipd** [comment]
Confirmed working:

Step 34 : RUN cat /etc/hostapd/hostapd.conf
 ---> Running in 705b2f800fbc
interface=ap0
driver=${RADIO_DRIVER}
country_code=${AP_COUNTRY}
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
ssid=${AP_SSID}
hw_mode=g
channel=${AP_CHAN}
beacon_int=100
auth_algs=1
wpa=0
macaddr_acl=0
wmm_enabled=1
ap_isolate=1
ieee80211n=1
 ---> f9c36526f545
Removing intermediate container 705b2f800fbc
Step 35 : RUN ep /etc/hostapd/hostapd.conf
 ---> Running in d973379374cd
 ---> 117b787ca736
Removing intermediate container d973379374cd
Step 36 : RUN cat /etc/hostapd/hostapd.conf
 ---> Running in 58f2561f05eb
interface=ap0
driver=nl80211
country_code=GB
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
ssid=ohs_setup
hw_mode=g
channel=1
beacon_int=100
auth_algs=1
wpa=0
macaddr_acl=0
wmm_enabled=1
ap_isolate=1
ieee80211n=1

**Comment by yawn** [comment]
I've released a RC for 1.0.0. Feel free to test and close if this fixes your issues.

**Comment by yawn** [comment]
Ping @memolipd

**Comment by memolipd** [comment]
I wont be able to test the release, but as said above the binary works fine.

**Comment by yawn** [comment]
👍

**Comment by memolipd** [comment]
We're trying to run this on a Pi Zero but it fails due to the zero being a ARM and not ARM7.

Any chance someone can throw up a ARM binary? I've tried compiling the go code but its not easy!
