### ISSUE TITLE
doubled binary size

### ISSUE THREAD

**Issue by DanielDent** [kreuzwerker/envplate#22]
The latest RC binary release is about twice as large as the historical releases. Is this a debug build?

It's only a couple megabytes more, but I'm curious if you know why the size jumped so much.

**Comment by yawn** [comment]
It has a few (transitive) dependencies more, but I did miss this increase in size. Is this an issue for you? If so I can certainly take a look into it ...

**Comment by DanielDent** [comment]
It's not really a big deal, I just try to be mindful of keeping my docker containers smaller where possible. Appreciate the offer though.
