### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by Yamakasi** [kreuzwerker/envplate#35]
I'm new to Go and would like to build this package so I can use it on Ubuntu.

Anyone some directions / examples ?

Thanks!

**Comment by hacfi** [comment]
@Yamakasi First you'll need to install [Go](https://golang.org/doc/install), [gox](https://github.com/mitchellh/gox) and [godep](https://github.com/tools/godep). Then you get the code by running `go get -u github.com/kreuzwerker/envplate` or by cloning this repository. If you used to `go get` you can go to the cloned repository by running `cd $GOPATH/src/github.com/kreuzwerker/envplate`. Then you install the dependencies with `godep restore` and run `make build` to build the executable.

**Comment by Yamakasi** [comment]
@hacfi Thanks a lot for the explanation! This project made my life so perfect, I'm happy! Thanks!
