### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by lrkwz** [kreuzwerker/envplate#36]
Is there a well known alternative?

maybe https://github.com/a8m/envsubst

**Comment by yawn** [comment]
It's not really abandoned, it's just that internally we didn't really use it that much anymore. Given that is has now > 200 stars we should give it a brush up though - is there anything that troubles you with it right now?

**Comment by lrkwz** [comment]
Well not really just a few issues opened and a scary v0.0.8 while a 1.0.0 seems to be ready to be released since years.

**Comment by yawn** [comment]
I think we're still using a latest version quite heavily internally @brotbert?
