### ISSUE TITLE
Make more easier to install in multiple arch docker image

### ISSUE THREAD

**Issue by guyskk** [kreuzwerker/envplate#43]
I find it's not easy to install envplate in multiple arch docker image, because I need check system arch by shell, then curl the corresponding envplate package.

### Proposal 1

Build a multiple arch docker image, which contains `ep` binary in `/usr/local/bin`, and publish to dockerhub.

Then we can use docker multi-stage build to simply copy the `ep` binary to my image, docker will auto pick the correct arch. Eg:

```Dockerfile
FROM kreuzwerker/envplate as envplate
FROM nginx:stable-alpine
COPY --from envplate /usr/local/bin/ep /usr/local/bin/ep 
```

### Proposal 2

Compile envplate to Javascript which can use in cross-platform, and I see [njs](https://nginx.org/en/docs/njs/) already packaged in Nginx docker image, it can execute the Javascript file.

I tried use https://github.com/gopherjs/gopherjs to compile, but it seems not work because of syscall problem.

```bash
$ GOOS=linux GOARCH=amd64 ~/go/bin/gopherjs build bin/ep.go
$ node ep.js README.md
warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
2021/12/30 00:12:52 [ ERROR ] Zero files matched passed globs '[README.md]'
fatal error: all goroutines are asleep - deadlock!
```

I think Proposal 1 is more easier to implement, any thought?

**Comment by guyskk** [comment]
I just learned a simple command to download corresponding package https://github.com/a8m/envsubst, eg:
```
curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
chmod +x envsubst
```

And I implemented one solution via njs : https://github.com/guyskk/envsub-njs

So I'm closing this issue, feel free to reopen and discuss ideas.

**Comment by mavogel** [comment]
Hi @guyskk, you can do the same with `envplate` as well
```sh
wget -q https://github.com/kreuzwerker/envplate/releases/download/v1.0.2/envplate_1.0.2_$(uname -s)_$(uname -m).tar.gz -O - | tar xz
./envplate --version
```

**Comment by guyskk** [comment]
@mavogel Yes, how about add this command to README?

**Comment by mavogel** [comment]
yes :) thanks for the catch. Done in https://github.com/kreuzwerker/envplate/commit/f9d911aed98b9ccc38ad6a1380cb7b47bb654ed8. Forgot this while updating the release process in #40
